version: "3.1"

services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        container_name: backend
        env_file: .env
        ports:
            - "8080:8080"

    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        container_name: frontend
        ports: "3000:80"
