name: Frontend Container

on:
    push:
        branches: [master, stable]
    pull_request:
        branches: [master, stable]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build the frontend image
              run: docker build . --file ./frontend/Dockerfile --tag mowboard-frontend:$(date +%s)
